services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - backend
  
  migrations:
    image: migrate/migrate
    command: [
      "-path", "/migrations", 
      "-database", "postgres://postgres:example@postgres:5432/postgres?sslmode=disable", 
      "up" ]
    volumes:
      - ./db/migrations:/migrations
    depends_on:
      - postgres
    networks:
      - backend
  
      
  api:
    build: .
    depends_on:
      - postgres
      - migrations
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
    ports:
      - "8080:8080"
    networks:
      - backend

volumes:
  pgdata:

networks:
  backend:
